-- MySQL Script generated by MySQL Workbench
-- 08/06/16 20:31:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pk10
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pk10
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pk10` DEFAULT CHARACTER SET utf8 ;
USE `pk10` ;

-- -----------------------------------------------------
-- Table `pk10`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`goods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `goodname` VARCHAR(255) NULL DEFAULT NULL COMMENT '商品名称',
  `price` FLOAT NULL DEFAULT NULL COMMENT '商品价格',
  `goodsimg` VARCHAR(255) NULL DEFAULT NULL COMMENT '商品图片',
  `goodsnum` INT(11) NULL DEFAULT NULL COMMENT '商品剩余数量',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
COMMENT = '商品表';


-- -----------------------------------------------------
-- Table `pk10`.`lotteryhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`lotteryhistory` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '开奖时间',
  `lotterynum` VARCHAR(100) NULL DEFAULT NULL COMMENT '开奖号码',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pk10`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`notice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '通知ID',
  `content` VARCHAR(12000) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '通知内容',
  `title` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '通知标题',
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '通知创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB 
AUTO_INCREMENT = 9 
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `user` VARCHAR(255) CHARACTER SET 'ucs2' NULL DEFAULT NULL COMMENT '所属用户',
  `price` DOUBLE NULL DEFAULT NULL COMMENT '订单金额',
  `status` VARCHAR(45) CHARACTER SET 'ucs2' NULL DEFAULT NULL COMMENT '订单状态',
  `createdAt` DATETIME NULL DEFAULT NULL COMMENT '订单创建时间',
  `userinfo_openid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_userinfo1_idx` (`userinfo_openid` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8
COMMENT = '订单表';


-- -----------------------------------------------------
-- Table `pk10`.`orders_has_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`orders_has_goods` (
  `order_id` INT(11) NOT NULL,
  `goods_id` INT(11) NOT NULL,
  INDEX `fk_order_has_goods_goods1_idx` (`goods_id` ASC),
  INDEX `fk_order_has_goods_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_has_goods_goods1`
    FOREIGN KEY (`goods_id`)
    REFERENCES `pk10`.`goods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_goods_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `pk10`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`tokeninfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`tokeninfo` (
  `id` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `tokenid` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '获取token 信息的表，理论上每两个小时更新一次';


-- -----------------------------------------------------
-- Table `pk10`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`userinfo` (
  `openid` VARCHAR(255) NOT NULL COMMENT '用户唯一标示',
  `nickname` VARCHAR(255) NULL DEFAULT NULL COMMENT '用户昵称',
  `money` DOUBLE NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `tel` VARCHAR(21) NULL DEFAULT NULL,
  PRIMARY KEY (`openid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pk10`.`userbet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pk10`.`userbet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL COMMENT '玩法，主要分 ‘单双’ ‘数字’ ‘大小’',
  `betmoney` DOUBLE NULL DEFAULT NULL COMMENT '下注金额',
  `mulit` INT(11) NULL DEFAULT NULL COMMENT '下注倍数',
  `betnum` VARCHAR(10) NULL DEFAULT NULL COMMENT '下注号码, 也可以是 \'single\' \'double\' \'big\' \'small\' ',
  `createdAt` DATETIME NULL DEFAULT NULL,
  `userinfo_openid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_userbet_userinfo1_idx` (`userinfo_openid` ASC),
  CONSTRAINT `fk_userbet_userinfo1`
    FOREIGN KEY (`userinfo_openid`)
    REFERENCES `pk10`.`userinfo` (`openid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
